#ifndef DEPLOYEDPOINTPILLARMODEL__VISIBILITY_CONTROL_H_
#define DEPLOYEDPOINTPILLARMODEL__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define DEPLOYEDPOINTPILLARMODEL_EXPORT __attribute__ ((dllexport))
    #define DEPLOYEDPOINTPILLARMODEL_IMPORT __attribute__ ((dllimport))
  #else
    #define DEPLOYEDPOINTPILLARMODEL_EXPORT __declspec(dllexport)
    #define DEPLOYEDPOINTPILLARMODEL_IMPORT __declspec(dllimport)
  #endif
  #ifdef DEPLOYEDPOINTPILLARMODEL_BUILDING_LIBRARY
    #define DEPLOYEDPOINTPILLARMODEL_PUBLIC DEPLOYEDPOINTPILLARMODEL_EXPORT
  #else
    #define DEPLOYEDPOINTPILLARMODEL_PUBLIC DEPLOYEDPOINTPILLARMODEL_IMPORT
  #endif
  #define DEPLOYEDPOINTPILLARMODEL_PUBLIC_TYPE DEPLOYEDPOINTPILLARMODEL_PUBLIC
  #define DEPLOYEDPOINTPILLARMODEL_LOCAL
#else
  #define DEPLOYEDPOINTPILLARMODEL_EXPORT __attribute__ ((visibility("default")))
  #define DEPLOYEDPOINTPILLARMODEL_IMPORT
  #if __GNUC__ >= 4
    #define DEPLOYEDPOINTPILLARMODEL_PUBLIC __attribute__ ((visibility("default")))
    #define DEPLOYEDPOINTPILLARMODEL_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define DEPLOYEDPOINTPILLARMODEL_PUBLIC
    #define DEPLOYEDPOINTPILLARMODEL_LOCAL
  #endif
  #define DEPLOYEDPOINTPILLARMODEL_PUBLIC_TYPE
#endif
#endif  // DEPLOYEDPOINTPILLARMODEL__VISIBILITY_CONTROL_H_
// Generated 22-May-2024 17:12:41
 