function filter = initBboxFilter(Detection)
    
    dt = 1;
    cvel = [1 dt; 0 1];
    A = blkdiag(cvel,cvel,cvel,cvel);


    G1d = [dt^2/2;dt];
    Q1d = G1d*G1d';
    Q = blkdiag(Q1d,Q1d,Q1d,Q1d);

    H = [1 0 0 0 0 0 0 0;...
         0 0 1 0 0 0 0 0;...
         0 0 0 0 1 0 0 0;...
         0 0 0 0 0 0 1 0];

    state = [Detection.Measurement(1);...
             0;...
             Detection.Measurement(2);...
             0;...
             Detection.Measurement(3);...
             0;...
             Detection.Measurement(4);...
             0];

    L = 650;
    stateCov = diag([Detection.MeasurementNoise(1,1),...
                     L,...
                     Detection.MeasurementNoise(2,2),...
                     L,...
                     Detection.MeasurementNoise(3,3),...
                     L,...
                     Detection.MeasurementNoise(4,4),...
                     L]);

    filter = trackingKF(...
                        'StateTransitionModel',A,...
                        'MeasurementModel',H,...
                        'State',state,...
                        'StateCovariance',stateCov,...
                        'MeasurementNoise',Detection.MeasurementNoise,...
                        'ProcessNoise',Q);

end