function msg = sensor_msgs_PointCloud2Struct
% Message struct definition for sensor_msgs/PointCloud2
coder.inline("never")
msg = struct(...
    'MessageType','sensor_msgs/PointCloud2',...
    'header',std_msgs_HeaderStruct,...
    'height',ros.internal.ros2.messages.ros2.default_type('uint32',1,0),...
    'width',ros.internal.ros2.messages.ros2.default_type('uint32',1,0),...
    'fields',sensor_msgs_PointFieldStruct,...
    'is_bigendian',ros.internal.ros2.messages.ros2.default_type('logical',1,0),...
    'point_step',ros.internal.ros2.messages.ros2.default_type('uint32',1,0),...
    'row_step',ros.internal.ros2.messages.ros2.default_type('uint32',1,0),...
    'data',ros.internal.ros2.messages.ros2.default_type('uint8',NaN,1),...
    'is_dense',ros.internal.ros2.messages.ros2.default_type('logical',1,0));
coder.cstructname(msg,'sensor_msgs_PointCloud2Struct_T');
coder.varsize('msg.fields',[1000000000 1],[1 0]);
coder.varsize('msg.data',[1000000000 1],[1 0]);
msg.fields = msg.fields([],1);
if ~isempty(coder.target)
    coder.ceval('//',coder.rref(msg));
end
end
